- marker_id: 10
  id: "green_bin"
  label: green_bin
  description: "green_bin"
  file: "obj/green_bin.obj"
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 1.57
    y: 0.0
    z: 0.0
  color:
    r: 0.0
    g: 0.0
    b: 0.0
    a: 0.0
- marker_id: 11
  id: "blue_bin"
  label: blue_bin
  description: "blue_bin"
  file: "obj/blue_bin.obj"
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 1.57
    y: 0.0
    z: 0.0
  color:
    r: 0.0
    g: 0.0
    b: 0.0
    a: 0.0
