base_config:
  position_tolerance: 0.005

controller_config:
 end_effectors: ['l_gripper_joint', 'r_gripper_joint']
 controllers:
   - l_arm_controller:
      goal_time: 0.6
      joints: ['l_shoulder_pan_joint', 'l_shoulder_lift_joint', 'l_upper_arm_roll_joint', 'l_elbow_flex_joint', 'l_forearm_roll_joint', 'l_wrist_flex_joint', 'l_wrist_roll_joint']
   - r_arm_controller:
      goal_time: 0.6
      joints: ['r_shoulder_pan_joint', 'r_shoulder_lift_joint', 'r_upper_arm_roll_joint', 'r_elbow_flex_joint', 'r_forearm_roll_joint', 'r_wrist_flex_joint', 'r_wrist_roll_joint']
