# The paths are relative to the 'cad_models_additional_search_path' param
# positions are in meters and orientations in radians
- id: "env"
  label: "background"
  description: "floor"
  file: "urdf/floor.urdf"
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "table"
  label: "table"
  description: "table"
  file: "urdf/table.urdf"
  position:
    x: 0.0
    y: 1.0
    z: 0.35
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
